"""Deterministic M1 golden session and explicit v0.1 release gate."""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import json
import subprocess
import sys
import tempfile
from collections.abc import Mapping
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any, Literal
from uuid import NAMESPACE_URL, UUID, uuid5

from deferred_teleop.mission_view import MissionViewState
from deferred_teleop.protocol import (
    ContractState,
    ExecutionContract,
    ExecutionEvent,
    MessageEnvelope,
    OperationPlan,
    ProvenanceKind,
    RobotForecast,
    SiteSnapshot,
    TaskAssignment,
)
from deferred_teleop.runtime import (
    DummyRobotService,
    EnvelopeFactory,
    FieldService,
    MissionService,
)
from deferred_teleop.storage import NodeStore

REPOSITORY_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_GOLDEN_ROOT = REPOSITORY_ROOT / "fixtures" / "m1" / "golden-session"
DEFAULT_MATRIX_PATH = REPOSITORY_ROOT / "release" / "m1" / "scenario-matrix.json"
DEFAULT_CHECKLIST_PATH = REPOSITORY_ROOT / "release" / "m1" / "release-checklist.json"
GOLDEN_EPOCH = datetime(2026, 9, 4, 12, 0, tzinfo=UTC)
ARTIFACT_NAMES = (
    "messages.jsonl",
    "expected-domain-state.json",
    "expected-mission-view.json",
    "expected-effect-counter.json",
    "README.md",
)
DELIVERY_KEYS = frozenset(
    {
        "delivery_index",
        "virtual_time_seconds",
        "delivery_kind",
        "source",
        "destination",
        "duplicate_of",
        "accepted_as_new",
        "envelope",
    }
)
REQUIRED_SCENARIOS = (
    "reliable-short-delay",
    "duplicated-intent",
    "duplicated-execution-contract",
    "ack-duplication-reordering",
    "blackout-before-field-receipt",
    "blackout-after-field-acceptance",
    "mission-restart-pending-outbox",
    "field-restart-after-admission",
    "dummy-restart-after-dispatch",
    "effect-before-terminal-delivery",
    "stale-expired-operation",
    "malformed-message-isolation",
    "low-bandwidth-control-plane",
    "unreal-mission-disconnect-reconnect",
)


class ReleaseGateError(RuntimeError):
    """Raised when committed release evidence is incomplete or inconsistent."""


@dataclass
class GoldenClock:
    current: datetime = GOLDEN_EPOCH

    def now(self) -> datetime:
        return self.current

    async def sleep(self, seconds: float) -> None:
        self.advance(seconds)

    def advance(self, seconds: float) -> None:
        if seconds < 0:
            raise ValueError("golden-session time cannot move backwards")
        self.current += timedelta(seconds=seconds)


@dataclass
class StableUuidFactory:
    node_id: str
    sequence: int = 0

    def __call__(self) -> UUID:
        self.sequence += 1
        return uuid5(NAMESPACE_URL, f"dtt-golden:{self.node_id}:{self.sequence}")


def _factory(node_id: str, clock: GoldenClock) -> EnvelopeFactory:
    return EnvelopeFactory(
        node_id,
        clock,
        boot_id=uuid5(NAMESPACE_URL, f"dtt-golden-boot:{node_id}"),
        uuid_factory=StableUuidFactory(node_id),
    )


def _json_text(value: object) -> str:
    return json.dumps(value, indent=2, sort_keys=True) + "\n"


def _jsonl_text(values: list[dict[str, Any]]) -> str:
    return "".join(
        json.dumps(value, separators=(",", ":"), sort_keys=True) + "\n" for value in values
    )


def _sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def _fixture_readme() -> str:
    return """# M1 golden session

This directory is the compact, reviewable reference session for the no-hardware
`PRESS_BUTTON` slice. The records are generated by the real Python domain services with a
fixed clock and UUID stream, then replayed and compared byte-for-byte by the release gate.

`messages.jsonl` is an ordered delivery log. `TRANSPORT_RETRANSMISSION` repeats the same
immutable envelope and `SEMANTIC_DUPLICATE` uses a new envelope identity for the same
contract. Both must converge on one durable dummy effect.

The strict `expected-mission-view.json` is the presentation-neutral `dtt/0` frame consumed
by Unreal. It keeps measured confirmation, predicted arrival and the operator-asserted target
separate. No record enables a physical or simulated actuator path.

Arrival carries a `PredictionManifest`. The target deliberately carries an operator-assertion
manifest and condition instead of being mislabeled as a prediction; both are recorded under
`projection_manifests` in `expected-domain-state.json`.

Regenerate and verify from the repository root:

```text
python -m deferred_teleop.release_gate generate
python -m deferred_teleop.release_gate verify --scope ci --skip-pytest
```

Run the complete automated matrix and the final release decision with:

```text
python -m deferred_teleop.release_gate verify --scope release
```

The release command intentionally remains non-zero while a mandatory manual/platform item
in `release/m1/release-checklist.json` is not `PASSED`.
"""


async def _build_golden_values(data_dir: Path) -> dict[str, Any]:
    clock = GoldenClock()
    deliveries: list[dict[str, Any]] = []

    with (
        NodeStore(data_dir / "mission.db") as mission_store,
        NodeStore(data_dir / "field.db") as field_store,
        NodeStore(data_dir / "robot.db") as robot_store,
    ):
        mission = MissionService(
            mission_store,
            _factory("mission-1", clock),
            configured_one_way_delay=0.25,
        )
        field = FieldService(field_store, _factory("field-1", clock))
        robot = DummyRobotService(
            robot_store,
            _factory("dummy-robot-1", clock),
            phase_duration=0.01,
        )
        mission.set_link_connected(True)

        async def deliver(
            service: MissionService | FieldService | DummyRobotService,
            envelope: MessageEnvelope,
            *,
            delay: float,
            kind: Literal[
                "ORIGINAL", "TRANSPORT_RETRANSMISSION", "SEMANTIC_DUPLICATE"
            ] = "ORIGINAL",
            duplicate_of: UUID | None = None,
        ) -> bool:
            clock.advance(delay)
            is_new = service.store.receive(envelope, received_at=clock.now())
            deliveries.append(
                {
                    "delivery_index": len(deliveries) + 1,
                    "virtual_time_seconds": round(
                        (clock.now() - GOLDEN_EPOCH).total_seconds(), 6
                    ),
                    "delivery_kind": kind,
                    "source": envelope.source_id,
                    "destination": envelope.destination_id,
                    "duplicate_of": str(duplicate_of) if duplicate_of else None,
                    "accepted_as_new": is_new,
                    "envelope": envelope.model_dump(mode="json"),
                }
            )
            if is_new:
                await service.handle(envelope)
            return is_new

        intent = mission.submit_press_button(expires_in_seconds=60.0)
        await deliver(field, intent, delay=0.25)
        await deliver(
            field,
            intent,
            delay=0.01,
            kind="TRANSPORT_RETRANSMISSION",
            duplicate_of=intent.message_id,
        )

        field_messages = field_store.outbox_messages()
        assignment = next(
            message for message in field_messages if isinstance(message.payload, TaskAssignment)
        )
        contract = next(
            message for message in field_messages if isinstance(message.payload, ExecutionContract)
        )

        # The contract arrives before its prerequisite. The Robot persists and retries it
        # after the assignment arrives, then commits the effect once.
        await deliver(robot, contract, delay=0.10)
        await deliver(robot, assignment, delay=0.01)
        original_robot_messages = robot_store.outbox_messages()

        semantic_duplicate = contract.model_copy(
            update={
                "message_id": uuid5(NAMESPACE_URL, "dtt-golden:duplicate-contract"),
                "source_sequence": contract.source_sequence + 100,
            }
        )
        await deliver(
            robot,
            semantic_duplicate,
            delay=0.02,
            kind="SEMANTIC_DUPLICATE",
            duplicate_of=contract.message_id,
        )

        terminal_replays = [
            message
            for message in robot_store.outbox_messages()
            if message.message_id
            not in {original.message_id for original in original_robot_messages}
        ]
        duplicated_forecast: MessageEnvelope | None = None
        for message in original_robot_messages:
            await deliver(field, message, delay=0.01)
            if isinstance(message.payload, RobotForecast) and duplicated_forecast is None:
                duplicated_forecast = message
                await deliver(
                    field,
                    message,
                    delay=0.001,
                    kind="TRANSPORT_RETRANSMISSION",
                    duplicate_of=message.message_id,
                )

        delivered_to_mission: set[UUID] = set()
        for message in field_store.outbox_messages():
            if message.destination_id != "mission-1" or message.message_id in delivered_to_mission:
                continue
            await deliver(mission, message, delay=0.01)
            delivered_to_mission.add(message.message_id)

        final_snapshot = next(
            message
            for message in reversed(field_store.outbox_messages())
            if isinstance(message.payload, SiteSnapshot)
            and message.destination_id == "mission-1"
        )
        await deliver(
            mission,
            final_snapshot,
            delay=0.001,
            kind="TRANSPORT_RETRANSMISSION",
            duplicate_of=final_snapshot.message_id,
        )

        view = mission.view_state().model_dump(mode="json")
        journal = robot_store.inspect_execution_journal()
        if len(journal) != 1:
            raise ReleaseGateError("golden session must produce exactly one execution journal")
        contract_history = robot_store.contract_history(
            UUID(journal[0]["contract_id"]), int(journal[0]["contract_revision"])
        )
        phases = [
            json.loads(item["metadata_json"])["phase"]
            for item in contract_history["audit"]
            if item["event_type"] == "dummy-skill-phase"
        ]
        invocation = next(
            json.loads(item["metadata_json"])
            for item in contract_history["audit"]
            if item["event_type"] == "skill-invocation"
        )
        plan = next(
            message for message in field_messages if isinstance(message.payload, OperationPlan)
        )
        grounded = next(
            message
            for message in field_messages
            if message.message_type == "operation.grounded"
        )
        terminal = next(
            message
            for message in original_robot_messages
            if isinstance(message.payload, ExecutionEvent)
            and message.payload.next_state is ContractState.SUCCEEDED
            and message.causation_id == contract.message_id
        )
        unique_envelopes = {
            record["envelope"]["message_id"]: record["envelope"] for record in deliveries
        }

        domain_state = {
            "schema_version": 1,
            "scenario_id": "m1-golden-press-button",
            "protocol_version": "dtt/0",
            "operation_id": str(intent.payload.operation_id),
            "correlation_id": str(intent.correlation_id),
            "plan_id": str(plan.payload.plan_id),
            "assignment_id": str(assignment.payload.assignment_id),
            "contract_id": str(contract.payload.contract_id),
            "contract_revision": contract.payload.contract_revision,
            "terminal_state": ContractState.SUCCEEDED.value,
            "capability_registry": list(robot.capabilities),
            "skill_phases": phases,
            "effect_key": journal[0]["effect_key"],
            "effect_counter": robot.effect_counter,
            "unique_envelope_count": len(unique_envelopes),
            "delivery_count": len(deliveries),
            "transport_retransmission_count": sum(
                record["delivery_kind"] == "TRANSPORT_RETRANSMISSION"
                for record in deliveries
            ),
            "semantic_duplicate_count": sum(
                record["delivery_kind"] == "SEMANTIC_DUPLICATE" for record in deliveries
            ),
            "terminal_replay_pending_count": len(terminal_replays),
            "provenance": {
                "confirmed": view["confirmed_state"]["evidence"]["provenance"],
                "arrival": view["arrival_belief"]["evidence"]["provenance"],
                "target": view["target_branch"]["evidence"]["provenance"],
            },
            "projection_manifests": {
                "arrival": view["prediction_manifests"][0],
                "target": {
                    "kind": "OPERATOR_TARGET_ASSERTION",
                    "condition": view["target_branch"]["condition"],
                    "source_ids": view["target_branch"]["evidence"]["source_ids"],
                    "provenance": view["target_branch"]["evidence"]["provenance"],
                    "world_revision": view["target_branch"]["evidence"]["world_revision"],
                },
            },
            "causal_chain": [
                {
                    "kind": "OperationIntent",
                    "id": str(intent.message_id),
                    "caused_by": None,
                },
                {
                    "kind": "GroundedOperation",
                    "id": str(grounded.message_id),
                    "caused_by": str(grounded.causation_id),
                },
                {
                    "kind": "OperationPlan",
                    "id": str(plan.message_id),
                    "caused_by": str(plan.causation_id),
                },
                {
                    "kind": "TaskAssignment",
                    "id": str(assignment.message_id),
                    "caused_by": str(assignment.causation_id),
                },
                {
                    "kind": "ExecutionContract",
                    "id": str(contract.message_id),
                    "caused_by": str(contract.causation_id),
                },
                {
                    "kind": "SkillInvocation",
                    "id": invocation["invocation_id"],
                    "caused_by": str(contract.message_id),
                },
                {
                    "kind": "DummyEffect",
                    "id": journal[0]["effect_key"],
                    "caused_by": invocation["invocation_id"],
                },
                {
                    "kind": "TerminalExecutionEvent",
                    "id": str(terminal.message_id),
                    "caused_by": str(terminal.causation_id),
                },
                {
                    "kind": "ReconciledSiteSnapshot",
                    "id": str(final_snapshot.message_id),
                    "caused_by": str(final_snapshot.causation_id),
                },
            ],
        }
        effect_counter = {
            "schema_version": 1,
            "scenario_id": "m1-golden-press-button",
            "contract_id": str(contract.payload.contract_id),
            "contract_revision": contract.payload.contract_revision,
            "effect_key": journal[0]["effect_key"],
            "expected_effect_counter": 1,
            "observed_effect_counter": robot.effect_counter,
            "invariant": "one contract revision produces no more than one dummy effect",
        }

    return {
        "messages": deliveries,
        "domain": domain_state,
        "view": view,
        "effect": effect_counter,
    }


def _render_artifacts(values: Mapping[str, Any]) -> dict[str, str]:
    return {
        "messages.jsonl": _jsonl_text(values["messages"]),
        "expected-domain-state.json": _json_text(values["domain"]),
        "expected-mission-view.json": _json_text(values["view"]),
        "expected-effect-counter.json": _json_text(values["effect"]),
        "README.md": _fixture_readme(),
    }


def _build_manifest(artifacts: Mapping[str, str], values: Mapping[str, Any]) -> dict[str, Any]:
    messages = values["messages"]
    return {
        "format_version": 1,
        "scenario_id": "m1-golden-press-button",
        "protocol_version": "dtt/0",
        "generated_at": GOLDEN_EPOCH.isoformat().replace("+00:00", "Z"),
        "generator": "python -m deferred_teleop.release_gate generate",
        "records": {
            "deliveries": len(messages),
            "unique_envelopes": len(
                {record["envelope"]["message_id"] for record in messages}
            ),
            "transport_retransmissions": sum(
                record["delivery_kind"] == "TRANSPORT_RETRANSMISSION"
                for record in messages
            ),
            "semantic_duplicates": sum(
                record["delivery_kind"] == "SEMANTIC_DUPLICATE" for record in messages
            ),
        },
        "features": [
            "initial-field-snapshot",
            "dummy-robot-capability-state-forecast",
            "delayed-and-duplicated-envelopes",
            "field-grounding-plan-assignment-contract",
            "dummy-skill-phases-and-effect-once",
            "mission-reconciliation",
            "arrival-and-target-prediction-manifests",
            "causal-graph",
            "strict-unreal-mission-view",
        ],
        "files": {
            name: {"sha256": _sha256_text(artifacts[name]), "bytes": len(artifacts[name].encode())}
            for name in ARTIFACT_NAMES
        },
    }


def generate_golden_session(root: Path = DEFAULT_GOLDEN_ROOT) -> dict[str, Any]:
    """Generate the deterministic committed fixture and return its manifest."""

    root.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix="dtt-golden-generate-") as temporary:
        values = asyncio.run(_build_golden_values(Path(temporary)))
    artifacts = _render_artifacts(values)
    manifest = _build_manifest(artifacts, values)
    for name, content in artifacts.items():
        (root / name).write_text(content, encoding="utf-8", newline="\n")
    (root / "manifest.json").write_text(
        _json_text(manifest), encoding="utf-8", newline="\n"
    )
    return manifest


def _load_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise ReleaseGateError(f"cannot read strict JSON artifact {path}: {error}") from error


def _load_messages(path: Path) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        try:
            record = json.loads(line)
        except json.JSONDecodeError as error:
            raise ReleaseGateError(f"invalid messages.jsonl line {line_number}: {error}") from error
        if not isinstance(record, dict) or set(record) != DELIVERY_KEYS:
            raise ReleaseGateError(f"unexpected delivery fields on line {line_number}")
        try:
            envelope = MessageEnvelope.model_validate_json(json.dumps(record["envelope"]))
        except ValueError as error:
            raise ReleaseGateError(
                f"invalid dtt/0 envelope on line {line_number}: {error}"
            ) from error
        if record["delivery_index"] != line_number:
            raise ReleaseGateError("delivery indices must be contiguous and one-based")
        if (
            record["source"] != envelope.source_id
            or record["destination"] != envelope.destination_id
        ):
            raise ReleaseGateError(f"delivery route mismatch on line {line_number}")
        records.append(record)
    return records


def _validate_duplicate_semantics(records: list[dict[str, Any]]) -> None:
    first_by_id: dict[str, dict[str, Any]] = {}
    for record in records:
        envelope = record["envelope"]
        message_id = envelope["message_id"]
        kind = record["delivery_kind"]
        duplicate_of = record["duplicate_of"]
        if kind == "ORIGINAL":
            if duplicate_of is not None:
                raise ReleaseGateError("original delivery cannot declare duplicate_of")
        elif kind == "TRANSPORT_RETRANSMISSION":
            original = first_by_id.get(str(duplicate_of))
            if original is None or original["envelope"] != envelope:
                raise ReleaseGateError("transport retransmission must repeat an earlier envelope")
            if record["accepted_as_new"]:
                raise ReleaseGateError("transport retransmission bypassed durable deduplication")
        elif kind == "SEMANTIC_DUPLICATE":
            original = first_by_id.get(str(duplicate_of))
            if original is None:
                raise ReleaseGateError("semantic duplicate must reference an earlier envelope")
            if original["envelope"]["message_id"] == message_id:
                raise ReleaseGateError("semantic duplicate requires a distinct envelope identity")
            for field in ("message_type", "correlation_id", "payload"):
                if original["envelope"][field] != envelope[field]:
                    raise ReleaseGateError(f"semantic duplicate changed immutable {field}")
        else:
            raise ReleaseGateError(f"unsupported delivery_kind: {kind}")
        first_by_id.setdefault(message_id, record)


def _validate_causation(records: list[dict[str, Any]]) -> None:
    envelopes = {
        record["envelope"]["message_id"]: record["envelope"] for record in records
    }
    for envelope in envelopes.values():
        causation_id = envelope.get("causation_id")
        if causation_id is not None and causation_id not in envelopes:
            raise ReleaseGateError(
                f"causation_id {causation_id} has no envelope in the golden session"
            )


def verify_golden_session(root: Path = DEFAULT_GOLDEN_ROOT) -> dict[str, Any]:
    """Strictly load, replay, and compare the committed golden session."""

    manifest = _load_json(root / "manifest.json")
    if not isinstance(manifest, dict) or manifest.get("format_version") != 1:
        raise ReleaseGateError("unsupported golden-session manifest")
    if manifest.get("protocol_version") != "dtt/0":
        raise ReleaseGateError("golden session must use dtt/0")
    files = manifest.get("files")
    if not isinstance(files, dict) or set(files) != set(ARTIFACT_NAMES):
        raise ReleaseGateError("golden-session manifest has an unexpected file set")
    for name in ARTIFACT_NAMES:
        content = (root / name).read_text(encoding="utf-8")
        expected = files[name]
        if _sha256_text(content) != expected.get("sha256"):
            raise ReleaseGateError(f"golden artifact checksum mismatch: {name}")
        if len(content.encode("utf-8")) != expected.get("bytes"):
            raise ReleaseGateError(f"golden artifact size mismatch: {name}")

    records = _load_messages(root / "messages.jsonl")
    if len(records) != manifest["records"]["deliveries"]:
        raise ReleaseGateError("golden delivery count differs from manifest")
    _validate_duplicate_semantics(records)
    _validate_causation(records)

    view = MissionViewState.model_validate_json(
        json.dumps(_load_json(root / "expected-mission-view.json"))
    )
    domain = _load_json(root / "expected-domain-state.json")
    effect = _load_json(root / "expected-effect-counter.json")
    if domain["terminal_state"] != ContractState.SUCCEEDED.value:
        raise ReleaseGateError("golden terminal state is not SUCCEEDED")
    if effect["expected_effect_counter"] != 1 or effect["observed_effect_counter"] != 1:
        raise ReleaseGateError("golden effect-once invariant is not satisfied")
    if (
        view.confirmed_state is None
        or view.confirmed_state.evidence.provenance is not ProvenanceKind.MEASURED
    ):
        raise ReleaseGateError("confirmed state must retain MEASURED provenance")
    if (
        view.arrival_belief is None
        or view.arrival_belief.evidence.provenance is not ProvenanceKind.PREDICTED
    ):
        raise ReleaseGateError("arrival belief must retain PREDICTED provenance")
    if (
        view.target_branch is None
        or view.target_branch.evidence.provenance is not ProvenanceKind.OPERATOR_ASSERTED
    ):
        raise ReleaseGateError("target branch must retain OPERATOR_ASSERTED provenance")

    with tempfile.TemporaryDirectory(prefix="dtt-golden-replay-") as temporary:
        replayed = asyncio.run(_build_golden_values(Path(temporary)))
    committed = {
        "messages": records,
        "domain": domain,
        "view": view.model_dump(mode="json"),
        "effect": effect,
    }
    if replayed != committed:
        raise ReleaseGateError("runtime replay differs from the committed golden result")
    return {
        "scenario_id": manifest["scenario_id"],
        "deliveries": len(records),
        "unique_envelopes": manifest["records"]["unique_envelopes"],
        "effect_counter": effect["observed_effect_counter"],
        "terminal_state": domain["terminal_state"],
        "mission_view": "strict-dtt/0",
    }


def validate_scenario_matrix(path: Path = DEFAULT_MATRIX_PATH) -> dict[str, Any]:
    matrix = _load_json(path)
    if not isinstance(matrix, dict) or matrix.get("format_version") != 1:
        raise ReleaseGateError("unsupported scenario-matrix format")
    scenarios = matrix.get("scenarios")
    if not isinstance(scenarios, list):
        raise ReleaseGateError("scenario matrix must contain a scenarios list")
    ids = [scenario.get("id") for scenario in scenarios if isinstance(scenario, dict)]
    if tuple(ids) != REQUIRED_SCENARIOS:
        raise ReleaseGateError(
            "scenario matrix is missing, reordering, or adding required profiles"
        )
    referenced_tests = 0
    for scenario in scenarios:
        tests = scenario.get("tests")
        if not isinstance(tests, list) or not tests:
            raise ReleaseGateError(f"scenario {scenario.get('id')} has no executable test")
        for node_id in tests:
            if not isinstance(node_id, str) or "::" not in node_id:
                raise ReleaseGateError(f"invalid pytest node id for {scenario.get('id')}")
            relative, function = node_id.split("::", 1)
            source = REPOSITORY_ROOT / relative
            if not source.is_file() or f"def {function}(" not in source.read_text(encoding="utf-8"):
                raise ReleaseGateError(f"missing matrix test: {node_id}")
            referenced_tests += 1
        evidence = scenario.get("evidence")
        if not isinstance(evidence, list) or not evidence:
            raise ReleaseGateError(f"scenario {scenario.get('id')} has no evidence reference")
        for relative in evidence:
            if not (REPOSITORY_ROOT / relative).is_file():
                raise ReleaseGateError(f"missing scenario evidence: {relative}")
    return {"scenarios": len(scenarios), "test_references": referenced_tests}


def _run_matrix_tests(path: Path = DEFAULT_MATRIX_PATH) -> dict[str, Any]:
    matrix = _load_json(path)
    node_ids = list(
        dict.fromkeys(
            node_id for scenario in matrix["scenarios"] for node_id in scenario["tests"]
        )
    )
    completed = subprocess.run(
        [sys.executable, "-m", "pytest", "-q", *node_ids],
        cwd=REPOSITORY_ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    return {
        "returncode": completed.returncode,
        "node_ids": node_ids,
        "stdout": completed.stdout,
        "stderr": completed.stderr,
    }


def evaluate_release_checklist(path: Path = DEFAULT_CHECKLIST_PATH) -> dict[str, Any]:
    checklist = _load_json(path)
    if not isinstance(checklist, dict) or checklist.get("format_version") != 1:
        raise ReleaseGateError("unsupported release-checklist format")
    items = checklist.get("items")
    if not isinstance(items, list) or not items:
        raise ReleaseGateError("release checklist has no items")
    allowed = {"PASSED", "BLOCKED"}
    invalid = [item.get("id") for item in items if item.get("status") not in allowed]
    if invalid:
        raise ReleaseGateError(f"release checklist has invalid statuses: {invalid}")
    blockers = [item for item in items if item["status"] != "PASSED"]
    return {
        "passed": len(items) - len(blockers),
        "total": len(items),
        "blockers": blockers,
        "release_ready": not blockers,
    }


def _write_report(path: Path | None, report: Mapping[str, Any]) -> None:
    encoded = _json_text(report)
    if path is None:
        print(encoded, end="")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(encoded, encoding="utf-8", newline="\n")
    print(path)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    generate = subparsers.add_parser("generate")
    generate.add_argument("--output", type=Path, default=DEFAULT_GOLDEN_ROOT)
    verify = subparsers.add_parser("verify")
    verify.add_argument("--golden-root", type=Path, default=DEFAULT_GOLDEN_ROOT)
    verify.add_argument("--matrix", type=Path, default=DEFAULT_MATRIX_PATH)
    verify.add_argument("--checklist", type=Path, default=DEFAULT_CHECKLIST_PATH)
    verify.add_argument("--scope", choices=("ci", "release"), default="release")
    verify.add_argument("--skip-pytest", action="store_true")
    verify.add_argument("--report", type=Path)
    return parser


def main() -> None:
    args = _build_parser().parse_args()
    if args.command == "generate":
        print(_json_text(generate_golden_session(args.output)), end="")
        return

    try:
        golden = verify_golden_session(args.golden_root)
        matrix = validate_scenario_matrix(args.matrix)
        tests = None if args.skip_pytest else _run_matrix_tests(args.matrix)
        checklist = evaluate_release_checklist(args.checklist)
        automated_ready = tests is None or tests["returncode"] == 0
        report = {
            "gate": "m1-v0.1",
            "scope": args.scope,
            "golden_session": golden,
            "scenario_matrix": matrix,
            "pytest": tests,
            "checklist": checklist,
            "automated_ready": automated_ready,
            "release_ready": automated_ready and checklist["release_ready"],
        }
        _write_report(args.report, report)
    except (OSError, KeyError, TypeError, ValueError, ReleaseGateError) as error:
        _write_report(
            getattr(args, "report", None),
            {"gate": "m1-v0.1", "scope": args.scope, "error": str(error)},
        )
        raise SystemExit(2) from error

    if not automated_ready or (args.scope == "release" and not checklist["release_ready"]):
        raise SystemExit(1)


if __name__ == "__main__":
    main()
