"""Validation helpers for named articulated dtt/0 robot state.

The wire model deliberately does not load a robot description.  This module is the explicit
boundary where a received state is checked against one description and converted to its
deterministic revolute-joint order.  Invalid input never produces a zero or fallback vector.
"""

from __future__ import annotations

import hashlib
import json
import math
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from pydantic import ValidationError

from deferred_teleop.protocol import ArticulatedRobotState

REPOSITORY_ROOT = Path(__file__).resolve().parents[4]
DEFAULT_SO101_DESCRIPTION_PATH = (
    REPOSITORY_ROOT / "robots" / "so101" / "generated" / "so101.kinematics.json"
)


@dataclass(frozen=True, slots=True)
class ArticulatedStateValidationResult:
    """Explicit outcome of description-backed articulated-state validation."""

    valid: bool
    diagnostics: tuple[str, ...]
    ordered_positions: tuple[float, ...]


def description_hash_for_bytes(data: bytes) -> str:
    """Return the protocol description hash for the exact generated bytes."""

    return f"sha256:{hashlib.sha256(data).hexdigest()}"


def description_hash_for_file(path: Path) -> str:
    """Hash a generated description without normalising or reserialising it."""

    return description_hash_for_bytes(path.read_bytes())


def _load_description(
    description: Mapping[str, Any] | Path | str,
) -> tuple[Mapping[str, Any] | None, str | None, tuple[str, ...]]:
    if isinstance(description, (Path, str)):
        path = Path(description)
        try:
            raw = path.read_bytes()
            parsed = json.loads(raw)
        except (OSError, UnicodeDecodeError, json.JSONDecodeError) as error:
            return None, None, (f"description cannot be loaded: {error}",)
        if not isinstance(parsed, Mapping):
            return None, description_hash_for_bytes(raw), ("description must be a JSON object",)
        return parsed, description_hash_for_bytes(raw), ()
    if isinstance(description, Mapping):
        return description, None, ()
    return None, None, ("description must be a mapping or JSON path",)


def _state_from_input(
    state: ArticulatedRobotState | Mapping[str, Any],
) -> tuple[ArticulatedRobotState | None, tuple[str, ...]]:
    if isinstance(state, ArticulatedRobotState):
        return state, ()
    if isinstance(state, Mapping):
        try:
            return ArticulatedRobotState.model_validate(state), ()
        except ValidationError as strict_error:
            # ``model_validate`` intentionally remains strict for Python objects.  A mapping
            # loaded from a JSON fixture carries JSON strings/lists, so validate that boundary
            # through Pydantic's JSON parser before reporting the original error.
            try:
                return ArticulatedRobotState.model_validate_json(json.dumps(state)), ()
            except (TypeError, ValueError, ValidationError) as json_error:
                error = json_error if isinstance(json_error, ValidationError) else strict_error
                return None, tuple(
                    f"state validation error: {item['loc']}: {item['msg']}"
                    for item in error.errors()
                )
    return None, ("state must be ArticulatedRobotState or a mapping",)


def _description_joints(
    description: Mapping[str, Any],
) -> tuple[dict[str, Mapping[str, Any]], tuple[str, ...]]:
    raw_joints = description.get("joints")
    if not isinstance(raw_joints, list):
        return {}, ("description.joints must be an array",)

    by_name: dict[str, Mapping[str, Any]] = {}
    diagnostics: list[str] = []
    for index, raw_joint in enumerate(raw_joints):
        if not isinstance(raw_joint, Mapping):
            diagnostics.append(f"description.joints[{index}] must be an object")
            continue
        name = raw_joint.get("name")
        if not isinstance(name, str) or not name.strip():
            diagnostics.append(f"description.joints[{index}].name must be non-blank")
            continue
        if name in by_name:
            diagnostics.append(f"description has duplicate joint name: {name}")
            continue
        by_name[name] = raw_joint
    return by_name, tuple(diagnostics)


def validate_articulated_state(
    state: ArticulatedRobotState | Mapping[str, Any],
    description: Mapping[str, Any] | Path | str = DEFAULT_SO101_DESCRIPTION_PATH,
    expected_description_hash: str | None = None,
) -> ArticulatedStateValidationResult:
    """Validate *state* against *description* and return its ordered revolute positions.

    ``expected_description_hash`` identifies the exact bytes the caller intended to use.  A
    path supplies an independently computed actual hash, while an in-memory mapping requires
    the caller to provide the expected hash explicitly.  Every mismatch is retained in
    ``diagnostics``; an invalid result has an empty ``ordered_positions`` tuple and never
    substitutes model defaults.
    """

    parsed_state, state_diagnostics = _state_from_input(state)
    parsed_description, actual_hash, description_diagnostics = _load_description(description)
    diagnostics = list(state_diagnostics) + list(description_diagnostics)
    ordered_positions: tuple[float, ...] = ()

    if parsed_state is None or parsed_description is None:
        return ArticulatedStateValidationResult(False, tuple(diagnostics), ordered_positions)

    reference = parsed_state.model_reference
    model_id = parsed_description.get("model_id")
    model_revision = parsed_description.get("model_revision")
    if reference.model_id != model_id:
        diagnostics.append(
            f"model_id mismatch: state={reference.model_id!r}, description={model_id!r}"
        )
    if reference.model_revision != model_revision:
        diagnostics.append(
            "model_revision mismatch: "
            f"state={reference.model_revision!r}, description={model_revision!r}"
        )

    if expected_description_hash is None:
        if actual_hash is None:
            diagnostics.append("expected description_hash is required for an in-memory description")
        else:
            expected_description_hash = actual_hash
    if (
        expected_description_hash is not None
        and reference.description_hash != expected_description_hash
    ):
        diagnostics.append(
            "description_hash mismatch: "
            f"state={reference.description_hash!r}, expected={expected_description_hash!r}"
        )
    if (
        actual_hash is not None
        and expected_description_hash is not None
        and actual_hash != expected_description_hash
    ):
        diagnostics.append(
            "expected description_hash does not match exact description bytes: "
            f"expected={expected_description_hash!r}, actual={actual_hash!r}"
        )

    joints_by_name, joint_diagnostics = _description_joints(parsed_description)
    diagnostics.extend(joint_diagnostics)
    revolute_names: list[str] = []
    for name, joint in joints_by_name.items():
        if joint.get("type") == "revolute":
            revolute_names.append(name)

    state_positions: dict[str, float] = {}
    for joint in parsed_state.joints:
        name = joint.joint_name
        value = joint.position_radians
        if not math.isfinite(value):
            diagnostics.append(f"joint {name} position_radians must be finite")
            continue
        description_joint = joints_by_name.get(name)
        if description_joint is None:
            diagnostics.append(f"unknown joint name: {name}")
            continue
        if description_joint.get("type") != "revolute":
            diagnostics.append(f"joint {name} is fixed or non-revolute")
            continue

        raw_limits = description_joint.get("position_limits_rad")
        if not isinstance(raw_limits, Mapping):
            diagnostics.append(f"joint {name} has no valid position limits")
            continue
        lower = raw_limits.get("lower")
        upper = raw_limits.get("upper")
        if (
            isinstance(lower, bool)
            or isinstance(upper, bool)
            or not isinstance(lower, (int, float))
            or not isinstance(upper, (int, float))
        ):
            diagnostics.append(f"joint {name} has invalid position limits")
            continue
        if (
            not math.isfinite(float(lower))
            or not math.isfinite(float(upper))
            or float(lower) > float(upper)
        ):
            diagnostics.append(f"joint {name} has invalid position limits")
            continue
        if value < float(lower):
            diagnostics.append(
                f"joint {name} violates lower limit: {value} < {float(lower)}"
            )
        if value > float(upper):
            diagnostics.append(
                f"joint {name} violates upper limit: {value} > {float(upper)}"
            )
        state_positions[name] = value

    for name in revolute_names:
        if name not in state_positions:
            diagnostics.append(f"missing required revolute joint: {name}")

    if not diagnostics:
        ordered_positions = tuple(state_positions[name] for name in revolute_names)
    return ArticulatedStateValidationResult(not diagnostics, tuple(diagnostics), ordered_positions)


__all__ = [
    "ArticulatedStateValidationResult",
    "DEFAULT_SO101_DESCRIPTION_PATH",
    "description_hash_for_bytes",
    "description_hash_for_file",
    "validate_articulated_state",
]
